### PR TITLE
`SimpleLexicon` tidy up.

### PR DESCRIPTION
**Pull request by jovilius**
Hi @dlwh, I'm very interested in your project and I would like to contribute to it. In this PR you can see some little improvements in term of style and syntax. Does it make sense for you?

Thanks, G.

### CODE REVIEW

**Comment by reactormonk** [comment]
Your first commit adds the executable bit to the file - could you fix that?

**Comment by dlwh** [comment]
lg otherwise

**Comment by dlwh** [comment]
(and thanks!)

**Comment by jovilius** [comment]
@reactormonk, @dlwh I've removed the executable bit in the first commit. 

What's your procedure to merge the PR into master? Do I need to have write access on `dlwh/epic` repo? Or will someone else merge for me?

Thanks, G.

**Comment by reactormonk** [comment]
Looks good according to @dlwh.

**Pull request merged**
